import Head from "next/head"

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>My profile | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Login</h1>
      </div>
    </>
  )
}
export default LoginPage
