import { content, heading } from "@/styles/font"

import Head from "next/head"
import { LOGIN } from "@/graphql/query"
import SubmitButton from "@/components/widgets/SubmitButton"
import TextField from "@mui/material/TextField"
import { useMutation } from "@apollo/client"
import { useState } from "react"

const LoginPage = ({
  setToken,
  setNewUser,
}: {
  setToken: any
  setNewUser: any
}) => {
  const [email, setEmail] = useState<string>("")
  const [password, setPassword] = useState<string>("")
  const [notification, setNotification] = useState<string>("")
  const [loginMutation] = useMutation(LOGIN, {
    onError: (error) => setNotification(error.message),
    onCompleted: (data) => {
      setToken(data.login)
      localStorage.setItem("new-user-token", data.login)
    },
  })

  const submit = (event: any) => {
    event.preventDefault()
    loginMutation({ variables: { email, password } })
    setPassword("")
  }

  return (
    <>
      <Head>
        <title>Log in | HD online platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="auth-content">
        <div className="loginForm">
          <h1 style={heading.style}>Login</h1>
          <form onSubmit={submit}>
            <div>
              <span>
                <p style={content.style}>Email: </p>
              </span>
              <TextField
                value={email}
                fullWidth
                required
                id="outlined-required"
                color="warning"
                onChange={({ target }) => setEmail(target.value)}
              />
            </div>
            <div>
              <span>
                <p style={content.style}>Password: </p>
              </span>
              <TextField
                type="password"
                value={password}
                fullWidth
                required
                color="warning"
                id="outlined-required"
                onChange={({ target }) => setPassword(target.value)}
              />
            </div>
            {notification.length > 0 && (
              <div className="notify">
                <p style={content.style}>Error: {notification}</p>
              </div>
            )}
            <SubmitButton title="Submit" />
          </form>
          <h4 style={heading.style} onClick={() => setNewUser(true)}>
            New user? Sign up here
          </h4>
        </div>
      </div>
    </>
  )
}
export default LoginPage
