import { MenuItem, TextField } from "@mui/material"
import { content, heading } from "@/styles/font"

import Head from "next/head"
import { SIGN_UP } from "@/graphql/query"
import SubmitButton from "@/components/widgets/SubmitButton"
import { useMutation } from "@apollo/client"
import { useState } from "react"

const SignUpPage = ({ setNewUser }: any) => {
  const [user, setUser] = useState<{
    name: string
    email: string
    role: string
  }>({
    name: "",
    email: "",
    role: "STUDENT",
  })
  const [password, setPassword] = useState<string>("")
  const [organization, setOrganization] = useState<string>("")

  const [notification, setNotification] = useState<string>("")
  const [signUpMutation] = useMutation(SIGN_UP, {
    onError: (error) => setNotification(error.message),
    onCompleted: (data) => {
      alert(
        `Welcome ${data.createUser.name} as a ${data.createUser.__typename}`
      )
      setNewUser(false)
    },
  })

  const submit = (event: any) => {
    event.preventDefault()
    if (user.role === "TEACHER") {
      signUpMutation({
        variables: {
          name: user.name,
          email: user.email,
          password,
          organization,
        },
      })
    } else {
      signUpMutation({
        variables: {
          name: user.name,
          email: user.email,
          password,
        },
      })
    }
    setPassword("")
    setUser({
      name: "",
      email: "",
      role: "STUDENT",
    })
  }

  return (
    <>
      <Head>
        <title>Sign up | HD online platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="auth-content">
        <div className="signupForm">
          <h1 style={heading.style}>Sign up</h1>
          <form onSubmit={submit}>
            <div>
              <span>
                <p style={content.style}>Name </p>
              </span>
              <TextField
                value={user.name}
                required
                color="warning"
                onChange={({ target }) =>
                  setUser({ ...user, name: target.value })
                }
                fullWidth
                size="small"
              />
            </div>
            <div>
              <span>
                <p style={content.style}>Email: </p>
              </span>
              <TextField
                value={user.email}
                required
                color="warning"
                onChange={({ target }) =>
                  setUser({ ...user, email: target.value })
                }
                fullWidth
                size="small"
              />
            </div>
            <div>
              <span>
                <p style={content.style}>Password:</p>
              </span>
              <TextField
                type="password"
                size="small"
                value={password}
                required
                color="warning"
                onChange={({ target }) => setPassword(target.value)}
                fullWidth
                helperText="At least 8 characters, contains both digits and letters"
              />
            </div>
            <div>
              <span>
                <p style={content.style}>Role:</p>
              </span>
              <TextField
                select
                required
                value={user.role}
                color="warning"
                onChange={({ target }) =>
                  setUser({ ...user, role: target.value })
                }
                fullWidth
                size="small"
              >
                {["STUDENT", "TEACHER"].map((role) => (
                  <MenuItem key={role} value={role}>
                    {role}
                  </MenuItem>
                ))}
              </TextField>
            </div>
            {user.role === "TEACHER" && (
              <div>
                <span>
                  <p style={content.style}>Your organization:</p>
                </span>
                <TextField
                  type="text"
                  value={organization}
                  required
                  color="warning"
                  onChange={({ target }) => setOrganization(target.value)}
                  fullWidth
                  size="small"
                />
              </div>
            )}
            {notification.length > 0 && (
              <div className="notify">
                <p style={content.style}>Error: {notification}</p>
              </div>
            )}
            <SubmitButton title="Continue" />
          </form>
          <h4 style={heading.style} onClick={() => setNewUser(false)}>
            Back to login
          </h4>
        </div>
      </div>
    </>
  )
}
export default SignUpPage
