import { content, heading } from "@/styles/font"

import Button from "@/components/widgets/Button"
import ContinueLink from "@/components/widgets/ContinueLink"
import { GET_CURRENT_USER } from "@/graphql/user_query"
import Head from "next/head"
import StudentCourseBoard from "@/components/dashboard/StudentCourseBoard"
import SuggestedCourses from "@/components/dashboard/SuggestedCourses"
import TeacherCourseBoard from "@/components/dashboard/TeacherCourseBoard"
import styles from "@/styles/Home.module.scss"
import { useQuery } from "@apollo/client"

export default function Home() {
  const user = useQuery(GET_CURRENT_USER, { pollInterval: 3000 })
  return (
    <>
      <Head>
        <title>Home | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(user.loading || (user.data && !user.data.getUser)) && (
        <div>
          <p style={content.style}>Loading, please wait ...</p>
        </div>
      )}
      {user.error && (
        <div>
          <p
            style={content.style}
          >{`There is an error: ${user.error.message}`}</p>
        </div>
      )}
      {user.data && user.data.getUser && (
        <div>
          <div className={styles.welcome}>
            <h1 style={heading.style}>Hello {user.data.getUser.name}!</h1>
            <p style={content.style}>It&#39;s nice to see you again!</p>
          </div>
          <div className={styles.currentCourses}>
            {user.data.getUser.__typename === "Student" ? (
              <StudentCourseBoard
                studyProgress={user.data.getUser.studyProgress}
              />
            ) : (
              <>
                <h2 style={heading.style}>Your own courses</h2>
                <TeacherCourseBoard ownCourses={user.data.getUser.ownCourses} />
                <ContinueLink
                  url="/profile/myprofile"
                  title="View more &#8594;"
                />
              </>
            )}
          </div>
          {user.data.getUser.__typename === "Student" ? (
            <SuggestedCourses />
          ) : (
            <div>
              <h2 style={heading.style}>Create a new course</h2>
              <Button
                title="Start"
                link={`/profile/new_course?tid=${user.data.getUser.id}`}
              />
            </div>
          )}
        </div>
      )}
    </>
  )
}
