import { content, heading } from "@/styles/font"

import Button from "@/components/widgets/Button"
import { GET_USER } from "@/graphql/user_query"
import Head from "next/head"
import StudentCourseBoard from "@/components/dashboard/StudentCourseBoard"
import SuggestedCourses from "@/components/dashboard/SuggestedCourses"
import TeacherCourseBoard from "@/components/dashboard/TeacherCourseBoard"
import TopicList from "@/components/dashboard/TopicList"
import styles from "@/styles/Home.module.scss"
import { useQuery } from "@apollo/client"

export default function Home() {
  const { loading, error, data } = useQuery(GET_USER)
  return (
    <>
      <Head>
        <title>Home | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && (
        <div>
          <p style={content.style}>Loading, please wait ...</p>
        </div>
      )}
      {error && (
        <div>
          <p style={content.style}>{`There is an error: ${error.message}`}</p>
        </div>
      )}
      {data && (
        <div>
          <div className={styles.welcome}>
            <h1 style={heading.style}>Hello {data.getUser.name}!</h1>
            <p style={content.style}>It&#39;s nice to see you again!</p>
          </div>
          <div className={styles.currentCourses}>
            {data.getUser.__typename === "Student" ? (
              <StudentCourseBoard studyProgress={data.getUser.studyProgress} />
            ) : (
              <TeacherCourseBoard id={data.getUser.id} />
            )}
          </div>
          <TopicList />
          {data.getUser.__typename === "Student" ? (
            <SuggestedCourses />
          ) : (
            <div>
              <h2 style={heading.style}>Create a new course</h2>
              <Button title="Start" link="/profile/newCourse" />
            </div>
          )}
        </div>
      )}
    </>
  )
}
