import { content, heading } from "@/styles/font"

import ContinueLink from "./components/widgets/ContinueLink"
import CourseCard from "./components/widgets/CourseCard"
import Head from "next/head"
import SuggestedCourses from "./components/dashboard/SuggestedCourses"
import TopicList from "./components/dashboard/TopicList"
import data from "@/pages/api/dummy.json"
import styles from "@/styles/Home.module.scss"

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.welcome}>
          <h1 style={heading.style}>Hello {data.user[0].name}!</h1>
          <p style={content.style}>It&#39;s nice to see you again!</p>
        </div>
        <div className={styles.currentCourses}>
          <h2 style={heading.style}>Ready to jump back on?</h2>
          <div>
            <CourseCard />
            <CourseCard />
          </div>
          <ContinueLink url="/profile" title="View more &#8594;" />
        </div>
        <TopicList />
        <SuggestedCourses />
      </div>
    </>
  )
}
