import Head from "next/head"
import { content } from "@/styles/font"

const LoadingPage = () => {
  return (
    <>
      <Head>
        <title>Home | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p style={content.style}>The page is loading. Please wait!</p>
      </div>
    </>
  )
}

export default LoadingPage
