import { content, heading } from "@/styles/font"

import Head from "next/head"
import StudyCourseTable from "./components/profile/StudyCourseTable"
import TeachingCourseTable from "./components/profile/TeachingCourseTable"
import data from "@/pages/api/dummy.json"
import styles from "@/styles/Profile.module.scss"

export default function Profile() {
  return (
    <>
      <Head>
        <title>My profile | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.header}>
          <h1 style={heading.style}>{data.user[0].name}</h1>
        </div>
        <div className={styles.profileInfo}>
          <table>
            <tbody>
              {data.user[0].roles == "TEACHER" && (
                <tr>
                  <th style={heading.style}>Organization</th>
                  <td style={content.style}>{data.user[0].organization}</td>
                </tr>
              )}
              <tr>
                <th style={heading.style}>Roles</th>
                <td style={content.style}>
                  {data.user[0].roles.toLowerCase()}
                </td>
              </tr>
              <tr>
                <th style={heading.style}>Email</th>
                <td style={content.style}>{data.user[0].email}</td>
              </tr>
              <tr>
                <th style={heading.style}>Municipality</th>
                <td style={content.style}>{data.user[0].municipality}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div className={styles.study}>
          <StudyCourseTable />
        </div>
        <div className={styles.teaching}>
          <TeachingCourseTable />
        </div>
      </div>
    </>
  )
}
