import Head from "next/head"

export default function Settings() {
  return (
    <>
      <Head>
        <title>Settings | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h1>Settings</h1>
        </div>
      </div>
    </>
  )
}
