import ContinueLink from "@/components/widgets/ContinueLink"
import { GET_COURSE_FULL } from "@/graphql/course_query"
import Head from "next/head"
import { KeyboardArrowRight } from "@mui/icons-material"
import LessonContent from "@/components/course/LessonContent"
import LessonQuiz from "@/components/course/LessonQuiz"
import { content } from "@/styles/font"
import { useQuery } from "@apollo/client"
import { useRouter } from "next/router"

const Lesson = () => {
  const router = useRouter()
  const { courseID, lessonID, which } = router.query
  const { loading, error, data } = useQuery(GET_COURSE_FULL, {
    variables: { getFullCourseId: courseID },
    pollInterval: 5000,
  })
  //@ts-ignore
  const lesson = data?.getFullCourse?.lessons.find((obj) => obj.id === lessonID)
  const index = data?.getFullCourse?.lessons.indexOf(lesson)
  return (
    <>
      <Head>
        <title>Lesson&apos;s ${which} | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lesson">
        {loading && (
          <p style={content.style}>The page is loading. Please wait!</p>
        )}
        {!lesson && <p style={content.style}>Some errors occurs! Try again</p>}
        {error && <p style={content.style}>Error: ${error.message}</p>}
        {data && (
          <>
            <div className="lessonNavBar">
              <ContinueLink
                url={`/${courseID}`}
                title={`${data.getFullCourse.name}`}
              />{" "}
              <KeyboardArrowRight />{" "}
              <p style={content.style}>{`${lesson.title}`}</p>{" "}
              <KeyboardArrowRight />
              <p style={content.style}>{` ${which}`}</p>
            </div>
            {which === "content" ? (
              <LessonContent
                title={`${index + 1} ${lesson.title}`}
                lessonContent={lesson.content}
              />
            ) : (
              <LessonQuiz
                title={`${index + 1} ${lesson.title}`}
                quizzes={lesson.quiz}
                courseID={courseID}
                lessonID={lessonID}
              />
            )}
          </>
        )}
      </div>
    </>
  )
}
export default Lesson
