import { GET_COURSE_BY_ID, GET_USER } from "@/graphql/query"

import ContinueLink from "@/components/widgets/ContinueLink"
import Head from "next/head"
import { KeyboardArrowRight } from "@mui/icons-material"
import LessonContent from "./LessonContent"
import LessonQuiz from "./LessonQuiz"
import { content } from "@/styles/font"
import { useQuery } from "@apollo/client"
import { useRouter } from "next/router"

const Lesson = () => {
  const router = useRouter()
  const { courseID, lessonID, which } = router.query
  const { loading, error, data } = useQuery(GET_COURSE_BY_ID, {
    variables: { getCourseByIdId: courseID },
  })
  const fetchUser = useQuery(GET_USER)

  //@ts-ignore
  const lesson = data.getCourseById.lessons.find((obj) => obj.id === lessonID)
  const index = data.getCourseById.lessons.indexOf(lesson)
  return (
    <>
      <Head>
        <title>Lesson&apos;s ${which} | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lesson">
        {(loading || fetchUser.loading) && (
          <p style={content.style}>The page is loading. Please wait!</p>
        )}
        {(error || !lesson || fetchUser.error) && (
          <p style={content.style}>Some errors occurs! Try again</p>
        )}
        {data && fetchUser.data && (
          <>
            <div className="lessonNavBar">
              <ContinueLink
                url={`/${courseID}`}
                title={`${data.getCourseById.name}`}
              />{" "}
              <KeyboardArrowRight />{" "}
              <p style={content.style}>{`${lesson.title}`}</p>{" "}
              <KeyboardArrowRight />
              <p style={content.style}>{` ${which}`}</p>
            </div>
            {which === "content" ? (
              <LessonContent
                title={`${index + 1} ${lesson.title}`}
                lessonContent={lesson.content}
              />
            ) : (
              <LessonQuiz
                title={`${index + 1} ${lesson.title}`}
                quizzes={lesson.quiz}
                courseID={courseID}
                lessonID={lessonID}
              />
            )}
          </>
        )}
      </div>
    </>
  )
}
export default Lesson
