import { ADD_QUIZ, GET_COURSE_FULL } from "@/graphql/course_query"
import { content, heading } from "@/styles/font"

import ContinueLink from "@/components/widgets/ContinueLink"
import Head from "next/head"
import SubmitButton from "@/components/widgets/SubmitButton"
import { TextField } from "@mui/material"
import { title } from "process"
import { useMutation } from "@apollo/client"
import { useRouter } from "next/router"
import { useState } from "react"

const NewQuizForm = () => {
  const { courseID, lessonID } = useRouter().query
  const [question, setQuestion] = useState("")
  const [answer, setAnswer] = useState("")
  const [choiceItem, setChoiceItem] = useState<string>("")
  const [choices, setChoices] = useState<string[]>([])
  const [notification, setNotification] = useState<{
    passed: boolean
    message: string
  }>({
    passed: true,
    message: "",
  })
  const [addQuiz] = useMutation(ADD_QUIZ, {
    onError: (error) =>
      setNotification({
        passed: false,
        message: error.message,
      }),
    onCompleted: () =>
      setNotification({
        passed: true,
        message:
          "Create new quiz done, return to the course page and see the result",
      }),
    refetchQueries: [
      { query: GET_COURSE_FULL, variables: { getFullCourseId: courseID } },
    ],
  })
  const addChoices = () => {
    setChoices(choices.concat(choiceItem))
    setChoiceItem("")
  }

  const submit = (e: any) => {
    e.preventDefault()
    addQuiz({
      variables: {
        lessonId: lessonID,
        question,
        choices,
        answer,
      },
    })
  }
  return (
    <>
      <Head>
        <title>Create new quiz | HD online platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="header">
          <h1 style={heading.style}>Create new quiz</h1>
        </div>
        <form onSubmit={submit} className="creationForm">
          <div>
            <span>
              <h3 style={heading.style}>Question</h3>
            </span>
            <TextField
              style={content.style}
              value={question}
              required
              color="warning"
              onChange={({ target }) => setQuestion(target.value)}
              fullWidth
              size="small"
            />
          </div>
          <div>
            <span>
              <h3 style={heading.style}>Choices</h3>
            </span>
            <div className="choiceBody">
              <textarea
                className="choiceBox"
                value={choiceItem}
                style={content.style}
                onChange={({ target }) => {
                  setChoiceItem(target.value)
                }}
              />
              <SubmitButton title="Add" onClick={addChoices} />
            </div>
            <div className="choiceList">
              <h3 style={heading.style}>List of question&apos;s choices: </h3>
              <p style={content.style}>{choices.join(", ")}</p>
            </div>
          </div>
          <div>
            <span>
              <h3 style={heading.style}>Correct answer</h3>
            </span>
            <textarea
              className="answerArea"
              value={answer}
              style={content.style}
              required
              onChange={({ target }) => {
                setAnswer(target.value)
              }}
            />
          </div>
          {notification.message.length === 0 ? (
            <SubmitButton title="Create" />
          ) : (
            <div
              className={
                notification.passed ? "passedMessage" : "failedMessage"
              }
            >
              {notification.passed ? (
                <p style={content.style}>
                  {notification.message}
                  <span>
                    <ContinueLink url={`/${courseID}`} title="this link" />
                  </span>
                </p>
              ) : (
                <p style={content.style}>{notification.message}</p>
              )}
            </div>
          )}
        </form>
      </div>
    </>
  )
}
export default NewQuizForm
