import { ADD_QUIZ, GET_COURSE_FULL } from "@/graphql/course_query"
import { IconButton, MenuItem, TextField } from "@mui/material"
import { content, heading } from "@/styles/font"

import ContinueLink from "@/components/widgets/ContinueLink"
import { Delete } from "@mui/icons-material"
import Head from "next/head"
import SubmitButton from "@/components/widgets/SubmitButton"
import { title } from "process"
import { useMutation } from "@apollo/client"
import { useRouter } from "next/router"
import { useState } from "react"

const NewQuizForm = () => {
  const { courseID, lessonID } = useRouter().query
  const [question, setQuestion] = useState("")
  const [answer, setAnswer] = useState("")
  const [choiceItem, setChoiceItem] = useState<string>("")
  const [choices, setChoices] = useState<string[]>([])
  const [notification, setNotification] = useState<{
    passed: boolean
    message: string
  }>({
    passed: true,
    message: "",
  })
  const [addQuiz] = useMutation(ADD_QUIZ, {
    onError: (error) =>
      setNotification({
        passed: false,
        message: error.message,
      }),
    onCompleted: () =>
      setNotification({
        passed: true,
        message:
          "Create new quiz done, return to the course page and see the result",
      }),
    refetchQueries: [
      { query: GET_COURSE_FULL, variables: { getFullCourseId: courseID } },
    ],
  })
  const addChoices = () => {
    setChoices(choices.concat(choiceItem))
    setChoiceItem("")
  }

  const submit = (e: any) => {
    e.preventDefault()
    if (choices.length > 0) {
      addQuiz({
        variables: {
          lessonId: lessonID,
          question,
          choices,
          answer,
        },
      })
    } else {
      addQuiz({
        variables: {
          lessonId: lessonID,
          question,
          answer,
        },
      })
    }
  }

  const deleteChoice = (removeChoice: string) => {
    setChoices([...choices.filter((choice) => choice !== removeChoice)])
  }
  return (
    <>
      <Head>
        <title>Create new quiz | HD online platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="header">
          <h1 style={heading.style}>Create new quiz</h1>
        </div>
        <form onSubmit={submit} className="creationForm">
          <div>
            <span>
              <h3 style={heading.style}>Question</h3>
            </span>
            <textarea
              className="choiceBox"
              style={content.style}
              value={question}
              required
              onChange={({ target }) => setQuestion(target.value)}
            />
          </div>
          <div>
            <span>
              <h3 style={heading.style}>Choices</h3>
            </span>
            <div className="choiceBody">
              <textarea
                className="choiceBox"
                value={choiceItem}
                style={content.style}
                onChange={({ target }) => {
                  setChoiceItem(target.value)
                }}
              />
              <SubmitButton title="Add" onClick={addChoices} />
            </div>

            {choices.length > 0 && (
              <div className="choiceList">
                <h3 style={heading.style}>List of question&apos;s choices: </h3>
                {choices.map((c) => (
                  <p key={c} style={content.style}>
                    {c}
                    <span>
                      <IconButton size="small" onClick={() => deleteChoice(c)}>
                        <Delete fontSize="inherit" />
                      </IconButton>
                    </span>
                  </p>
                ))}
              </div>
            )}
          </div>

          <div>
            <span>
              <h3 style={heading.style}>Correct answer</h3>
            </span>
            {choices.length > 0 ? (
              <TextField
                select
                required
                value={answer}
                color="warning"
                onChange={({ target }) => setAnswer(target.value)}
                fullWidth
                size="small"
              >
                {choices.map((correctChoice) => (
                  <MenuItem key={correctChoice} value={correctChoice}>
                    {correctChoice}
                  </MenuItem>
                ))}
              </TextField>
            ) : (
              <textarea
                className="answerArea"
                value={answer}
                style={content.style}
                required
                onChange={({ target }) => {
                  setAnswer(target.value)
                }}
              />
            )}
          </div>
          {notification.message.length === 0 ? (
            <SubmitButton title="Create" />
          ) : (
            <div
              className={
                notification.passed ? "passedMessage" : "failedMessage"
              }
            >
              {notification.passed ? (
                <p style={content.style}>
                  {notification.message}
                  <span>
                    <ContinueLink url={`/${courseID}`} title="this link" />
                  </span>
                </p>
              ) : (
                <p style={content.style}>{notification.message}</p>
              )}
            </div>
          )}
        </form>
      </div>
    </>
  )
}
export default NewQuizForm
