import { GET_STUDENT, GET_TEACHER_BY_ID } from "@/graphql/query"
import { content, heading } from "@/styles/font"

import Head from "next/head"
import TeachingCourseTable from "../components/profile/TeachingCourseTable"
import styles from "@/styles/Profile.module.scss"
import { useQuery } from "@apollo/client"
import { useRouter } from "next/router"

export default function Profile() {
  const router = useRouter()
  const { teacherID } = router.query
  const { loading, error, data } = useQuery(GET_TEACHER_BY_ID, {
    variables: { userID: teacherID },
  })
  return (
    <>
      <Head>
        <title>Teacher | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {loading && (
          <div>
            <p style={content.style}>Loading, please wait ...</p>
          </div>
        )}
        {error && (
          <div>
            <p style={content.style}>{`There is an error: ${error.message}`}</p>
          </div>
        )}
        {data && (
          <>
            <div className={styles.header}>
              <h1 style={heading.style}>{data.getTeacher.name}</h1>
            </div>
            <div className={styles.profileInfo}>
              <table>
                <tbody>
                  <tr>
                    <th style={heading.style}>Organization</th>
                    <td style={content.style}>
                      {data.getTeacher.organization}
                    </td>
                  </tr>
                  <tr>
                    <th style={heading.style}>Roles</th>
                    <td style={content.style}>
                      {data.getTeacher.roles.toLowerCase()}
                    </td>
                  </tr>
                  <tr>
                    <th style={heading.style}>Email</th>
                    <td style={content.style}>{data.getTeacher.email}</td>
                  </tr>
                  <tr>
                    <th style={heading.style}>Municipality</th>
                    <td style={content.style}>
                      {data.getTeacher.municipality}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div className={styles.teaching}>
              <TeachingCourseTable />
            </div>
          </>
        )}
      </div>
    </>
  )
}
