import { content, heading } from "@/styles/font"

import { GET_OTHER_TEACHER_BY_ID } from "@/graphql/user_query"
import Head from "next/head"
import StudyCourseTable from "@/components/profile/StudyCourseTable"
import TeachingCourseTable from "@/components/profile/TeachingCourseTable"
import error from "next/error"
import styles from "@/styles/Profile.module.css"
import { useQuery } from "@apollo/client"
import { useRouter } from "next/router"

export default function Profile() {
  const { teacherID } = useRouter().query
  const { loading, error, data } = useQuery(GET_OTHER_TEACHER_BY_ID, {
    variables: { userID: teacherID },
  })

  return (
    <>
      <Head>
        <title>Profile | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {loading && (
          <div>
            <p style={content.style}>Loading, please wait ...</p>
          </div>
        )}
        {error && (
          <div>
            <p
              style={content.style}
            >{`There is an error in loading profile: ${error.message}`}</p>
          </div>
        )}
        {data && (
          <>
            <div className={styles.header}>
              <h1 style={heading.style}>{data.getTeacher.name}</h1>
            </div>
            <div className="informationTable">
              <table>
                <tbody>
                  <tr>
                    <th style={heading.style}>Roles</th>
                    <td style={content.style}>Teacher</td>
                  </tr>
                  <tr>
                    <th style={heading.style}>Email</th>
                    <td style={content.style}>{data.getTeacher.email}</td>
                  </tr>
                  {data.getUser.__typename === "Teacher" && (
                    <tr>
                      <th style={heading.style}>Organization</th>
                      <td style={content.style}>
                        {data.getTeacher.organization}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>
    </>
  )
}
