import { content, heading } from "@/styles/font"

import { GET_OTHER_USER_BY_ID } from "@/graphql/user_query"
import Head from "next/head"
import TeacherCourseBoard from "@/components/dashboard/TeacherCourseBoard"
import styles from "@/styles/Profile.module.css"
import { useQuery } from "@apollo/client"
import { useRouter } from "next/router"

export default function Profile() {
  const { uID } = useRouter().query
  const { loading, error, data } = useQuery(GET_OTHER_USER_BY_ID, {
    variables: { userId: uID },
    // pollInterval: 2000,
  })

  return (
    <>
      <Head>
        <title>Profile | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {(loading || (data && !data.getOtherUser)) && (
          <div>
            <p style={content.style}>Loading, please wait ...</p>
          </div>
        )}
        {error && (
          <div>
            <p
              style={content.style}
            >{`There is an error in loading profile: ${error.message}`}</p>
          </div>
        )}
        {data && data.getOtherUser && (
          <>
            <div className={styles.header}>
              <h1 style={heading.style}>{data.getOtherUser.name}</h1>
            </div>
            <div className="informationTable">
              <table>
                <tbody>
                  <tr>
                    <th style={heading.style}>Roles</th>
                    <td style={content.style}>
                      {data.getOtherUser.__typename}
                    </td>
                  </tr>
                  <tr>
                    <th style={heading.style}>Email</th>
                    <td style={content.style}>{data.getOtherUser.email}</td>
                  </tr>
                  {data.getOtherUser.__typename === "Teacher" && (
                    <tr>
                      <th style={heading.style}>Organization</th>
                      <td style={content.style}>
                        {data.getOtherUser.organization}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            {data.getOtherUser.__typename === "Teacher" && (
              <div>
                <h2 style={heading.style}>Courses</h2>
                <TeacherCourseBoard ownCourses={data.getOtherUser.ownCourses} />
              </div>
            )}
          </>
        )}
      </div>
    </>
  )
}
