import { content, heading } from "@/styles/font"

import Head from "next/head"
import { LOGIN } from "@/graphql/query"
import TextField from "@mui/material/TextField"
import styles from "@/styles/Login.module.scss"
import { useMutation } from "@apollo/client"
import { useState } from "react"

const LoginPage = ({ setToken }: { setToken: any }) => {
  const [email, setEmail] = useState<string>("")
  const [password, setPassword] = useState<string>("")
  const [loginMutation] = useMutation(LOGIN, {
    onError: (error) => console.error(error),
    onCompleted: (data) => {
      setToken(data.login)
      localStorage.setItem("new-user-token", data.login)
    },
  })

  const submit = (event: any) => {
    event.preventDefault()
    loginMutation({ variables: { email, password } })
    setPassword("")
  }

  return (
    <>
      <Head>
        <title>Log in | HD learning platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.loginForm}>
        <h1 style={heading.style}>Login</h1>
        <form onSubmit={submit}>
          <div>
            <span>
              <p style={content.style}>Email: </p>
            </span>
            <TextField
              value={email}
              required
              id="outlined-required"
              color="warning"
              onChange={({ target }) => setEmail(target.value)}
            />
          </div>
          <div>
            <span>
              <p style={content.style}>Password: </p>
            </span>
            <TextField
              type="password"
              value={password}
              required
              color="warning"
              id="outlined-required"
              onChange={({ target }) => setPassword(target.value)}
            />
          </div>
          <button className="button" type="submit">
            <span style={content.style}>Submit</span>
          </button>
        </form>
      </div>
    </>
  )
}
export default LoginPage
